Put back ZoL stuff. + RAID-Z3 is availible on Linux. + Use 'zfs create -p' to simplify code. + Linux don't have a problem   with having multiple devices (mirror, raidzX etc) on either the /boot   or /lib/modules etc, so just skip and we're done. + Change "{Free,Used} physical volumes" to "... devices' which is more correct. + Hack for linux - remove ' free #X' from the device list line. Don't   know where that came from though... + Make post-base-installer.d/60partman-zfs executable. + Put the linux check before the get_zfs_root_boot() call. + No cache file on linux. * If Linux, create a v28 pool for now. ZoL   is using LZ4 to compress the meta data, but grub does not (yet!)   understand this so it will bail out to a rescue shell with:
      error: compression algorithm 143 not supported

+ Double check to make sure we don't have FS created in fs_create()
  already on separate partition. Such as having /boot on separate
  partition/outside the ZFS pool.
+ Remove duplicate get_vg_value().
+ On Linux, bail in pv_prepare() - we let zpool create the partition
  + If linux && num=-1 && fs=free => bail. Not needed.
+ Remove MD parts - ripped a little to clean from partman-md...
+ The /boot/zfs directory is needed when creating an initrd.
+ Build and install 'genhostid' from Red Hat, to create a /etc/hostid.
  + Execute it just before loading the module.
+ Move (and fix) the stuff in post-base-installer.d/60partman-zfs to finish.d/aptinstall_zfs.
+ Put back a simpler version of post-base-installer.d/60partman-zfs
  which only copies /boot/zfs and /etc/hostid if they exists.
+ Only setup features to enable if not Linux.

Signed-off-by: Turbo Fredriksson <turbo@bayour.com>